Pdm object tagger
dwp/dataworks-behavioural-framework pull request #152
Opened 2021-10-01 16:18 UTC by tobywalls

2021-10-05 13:31 UTC, rbryett requested changes

2021-10-05 13:31 UTC, rbryett commented on src/features/steps/pdm-dataset-generation.py
> +            s3_keys[:50],
Is there a scenario where we maybe checking the same keys over and over again? If so, should we take into consideration the last_modified date? If not, then ignore this comment.

2021-10-05 13:31 UTC, rbryett commented on src/helpers/object_tagger_helper.py
> +
From here, can we split up the logic below into other functions? Im thinking about the standalone object_tagger tests at this stage and also future tests that might require similar functionality.

That said, would it make sense to have a function, encapsulating what you have below, where you can pass in a db_name, table_name & the tags_dict to populate the **required_tags_list**, the aws_object_tags_list and return it back to the test. At that point make the assertion within the test code itself as opposed to making the assertion in a helper (for improved readability)?

2021-10-06 15:28 UTC, tobywalls commented on src/features/steps/pdm-dataset-generation.py
> +def step_impl(context):
Agreed - behaviour modified

2021-10-06 16:21 UTC, merged